improve vpslib helper functions

diff --git a/vpslib b/vpslib
--- a/vpslib
+++ b/vpslib
@@ -16,24 +16,32 @@
 set -Eeuo pipefail
 trap 'error "line $LINENO, code $?: $BASH_COMMAND"' ERR
 
-bold()    { tput bold; printf '%s' "$@"; tput sgr0; }
-red()     { tput setaf 1; bold "$@"; }
-green()   { tput setaf 2; bold "$@"; }
-fatal()   { echo $(red "${0##*/}" ': fatal' "${1:+: $1}") >&2; exit ${2:-1}; }
-error()   { echo $(red "${0##*/}" ': error' "${1:+: $@}") >&2; }
-message() { ((VPS_VERBOSE)) && echo $(green '* ' "$@") || :; }
+try()     { "$@" 2>/dev/null || :; }
+bold()    { try tput bold; printf '%s' "$@"; try tput sgr0; echo; }
+color()   { if (($# > 1)); then try tput setaf "$1"; shift; bold "$@"; fi; }
+red()     { color 1 "$@"; }
+green()   { color 2 "$@"; }
+yellow()  { color 3 "$@"; }
+blue()    { color 4 "$@"; }
+fatal()   { red "${0##*/}: fatal${1:+: $@}" >&2; exit 1; }
+error()   { red           "error${1:+: $@}" >&2; }
+warning() { yellow      "warning${1:+: $@}" >&2; }
+message() { if ((VPS_VERBOSE)); then green "* $@"; fi; }
+debugmsg(){ if ((VPS_DEBUG)); then echo       "$@" >&2; fi; }
+debugvar(){ if ((VPS_DEBUG)); then declare -p "$@" >&2; fi; }
 
-VPS_VERBOSE=${VPS_VERBOSE:-1}
-VPS_CONFIG=${1:-${VPS_CONFIG:-'/etc/vps/vps.conf'}}  # can't use VPS_SLUG here
-VPS_SLUG=${VPS_SLUG:-'vpssetup'}
-
+VPS_CONFIG=${VPS_CONFIG:-'/etc/vps/vps.conf'}  # can't use VPS_SLUG here
 if [[ -r "$VPS_CONFIG" ]]; then
 	set -a  # Export all non-array vars in config. Just for the check below
 	source "$VPS_CONFIG"
 	set +a
 fi
 
-message "Config file: $VPS_CONFIG"
+VPS_VERBOSE=${VPS_VERBOSE:-1}
+VPS_BATCH=${VPS_BATCH:-0}
+VPS_SLUG=${VPS_SLUG:-'vpssetup'}
+
+if ! ((VPS_BATCH)); then message "Config file: $VPS_CONFIG"; fi
 env | grep -q '^VPS_' 2>/dev/null ||
 	fatal "No config vars set. Check config file: $VPS_CONFIG"
 
